version: '3.8'

services:
  
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mongodb
      - php
      - node

  php:
    build:
      context: "."
      dockerfile: "dockerfiles/php.dockerfile"
    volumes:
      - ./src:/var/www/html:delegated
       
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  node:
    build: 
      context: .
      dockerfile: ./dockerfiles/npm.dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src/node_modules:/var/www/html/node_modules
      - ./src:/var/www/html:delegated
    ports:
      - 3000:3000    
    tty: true
    stdin_open: true

  npm:
    image: node:current-alpine3.19
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: ['npm']
    tty: true
    stdin_open: true

  mongodb:
    image: 'mongo'
    ports:
      - "5050:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: